### ISSUE TITLE
V4_Normalize: dot product is used as norm

### ISSUE THREAD

**Issue by amytnyk** [hollasch/ray4#11]
In file r4/src/r4_vec.c:
```
short V4_Normalize (Vector4 V)
{
    double norm; 

    norm = V4_Dot (V,V);

    if (norm < 1e-30) return 0;

    V4_Scalar (V, /=, norm);

    return 1;
}
```

Taking norm as dot product causes invalid lighting.

Sqrt of dot product should be taken

**Comment by hollasch** [comment]
Just saw this; oops! Thank you for the comment. You're right, I'll correct.

**Comment by hollasch** [comment]
And _man_, this code needs to be modernized.
