### ISSUE TITLE
linking fails (missing `-lm`) (fixed?)

### ISSUE THREAD

**Issue by claudeha** [hollasch/ray4#16]
As a CMake neophyte I'm not sure this is the best solution but it works for me:

```diff
diff --git a/ray4/CMakeLists.txt b/ray4/CMakeLists.txt
index 79cf8c9..a05d896 100644
--- a/ray4/CMakeLists.txt
+++ b/ray4/CMakeLists.txt
@@ -21,3 +21,4 @@ set ( sources_ray4
 )
 
 add_executable (ray4 ${sources_ray4})
+target_link_libraries(ray4 -lm)
```

**Comment by hollasch** [comment]
What platform are you building on? What toolset?

**Comment by claudeha** [comment]
On 28/07/2024 23:31, Steve Hollasch wrote:
>
> What platform are you building on? What toolset?
>
Was a while since I tested, but probably Debian amd64/x86_64 with gcc.

**Comment by hollasch** [comment]
I'm also pretty much a CMake neophyte, but I believe the following should fix the issue. After the `add_executable` line, I've added this:

```
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_link_libraries(ray4 m)
endif()
```

I'd really appreciate it if you could find the time to verify this. Thanks!

**Comment by hollasch** [comment]
Looks like it's fixed well enough for now.
